import {
  Activity,
  Archive,
  BellRing,
  Box,
  Boxes,
  Bug,
  Clock,
  Code,
  Cpu,
  Database,
  FileCode,
  FileLock,
  Folder,
  FolderSymlink,
  Gauge,
  Globe,
  HardDrive,
  Hexagon,
  LayoutDashboard,
  LayoutGrid,
  Network,
  Server,
  ServerCog,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Terminal,
  Users,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

// 后端 nav.icon 字段名(kebab-case)→ lucide 组件;未命中给兜底图标。
const ICONS: Record<string, LucideIcon> = {
  gauge: Gauge,
  dashboard: LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  server: Server,
  'server-cog': ServerCog,
  cpu: Cpu,
  'hard-drive': HardDrive,
  network: Network,
  activity: Activity,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-lock': ShieldCheck,
  terminal: Terminal,
  folder: Folder,
  'folder-symlink': FolderSymlink,
  clock: Clock,
  settings: Settings,
  boxes: Boxes,
  box: Box,
  'layout-grid': LayoutGrid,
  database: Database,
  globe: Globe,
  'file-code': FileCode,
  'file-lock': FileLock,
  hexagon: Hexagon,
  code: Code,
  bug: Bug,
  archive: Archive,
  'bell-ring': BellRing,
  users: Users,
}

/** iconFor 把后端 icon 字段名解析为 lucide 组件,缺省返回 Boxes。 */
export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Boxes
}
