import {
  Activity,
  Archive,
  BarChart2,
  BellRing,
  Box,
  Boxes,
  Bug,
  ScrollText,
  Clock,
  Coffee,
  Code,
  Cpu,
  Database,
  FileCode,
  FileLock,
  Folder,
  FolderSymlink,
  Gauge,
  GitBranch,
  GitFork,
  Globe,
  HardDrive,
  Hexagon,
  LayoutDashboard,
  LayoutGrid,
  Mail,
  Network,
  Server,
  ServerCog,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Terminal,
  Truck,
  Users,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

// 后端 nav.icon 字段名(kebab-case)→ lucide 组件;未命中给兜底图标。
const ICONS: Record<string, LucideIcon> = {
  gauge: Gauge,
  dashboard: LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  server: Server,
  'server-cog': ServerCog,
  cpu: Cpu,
  'hard-drive': HardDrive,
  network: Network,
  activity: Activity,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-lock': ShieldCheck,
  terminal: Terminal,
  folder: Folder,
  'folder-symlink': FolderSymlink,
  clock: Clock,
  settings: Settings,
  boxes: Boxes,
  box: Box,
  'layout-grid': LayoutGrid,
  database: Database,
  globe: Globe,
  'scroll-text': ScrollText,
  'file-code': FileCode,
  'file-lock': FileLock,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  mail: Mail,
  zap: Zap,
  hexagon: Hexagon,
  code: Code,
  bug: Bug,
  archive: Archive,
  'bell-ring': BellRing,
  coffee: Coffee,
  'bar-chart-2': BarChart2,
  truck: Truck,
  users: Users,
}

/** iconFor 把后端 icon 字段名解析为 lucide 组件,缺省返回 Boxes。 */
export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Boxes
}

// 侧栏图标按语义上色:深色上柔和雅致、可读,对标 aaPanel 的彩色友好导航。
// 同类归同色:概览/系统=蓝、文件/存储=暖金、网络/站点=青、数据库=紫、
// 安全=红、计划/任务=琥珀、容器/应用=靛、运行时/语言=各自代表色。
const ICON_COLORS: Record<string, string> = {
  gauge: 'text-sky-400',
  dashboard: 'text-sky-400',
  'layout-dashboard': 'text-sky-400',
  server: 'text-sky-400',
  'server-cog': 'text-sky-400',
  cpu: 'text-sky-400',
  activity: 'text-sky-400',
  'bar-chart-2': 'text-sky-400',
  'hard-drive': 'text-amber-400',
  folder: 'text-gold',
  'folder-symlink': 'text-gold',
  archive: 'text-amber-400',
  network: 'text-teal-400',
  globe: 'text-teal-400',
  truck: 'text-teal-400',
  database: 'text-violet-400',
  mysql: 'text-violet-400',
  postgres: 'text-violet-400',
  redis: 'text-rose-400',
  shield: 'text-rose-400',
  'shield-alert': 'text-rose-400',
  'shield-check': 'text-emerald-400',
  'shield-lock': 'text-rose-400',
  bug: 'text-rose-400',
  'file-lock': 'text-rose-400',
  clock: 'text-amber-300',
  'bell-ring': 'text-amber-300',
  boxes: 'text-indigo-400',
  box: 'text-indigo-400',
  'layout-grid': 'text-indigo-400',
  hexagon: 'text-indigo-400',
  'file-code': 'text-sky-400',
  code: 'text-sky-400',
  'git-branch': 'text-orange-400',
  'git-fork': 'text-orange-400',
  gitea: 'text-orange-400',
  mail: 'text-cyan-400',
  zap: 'text-amber-300',
  coffee: 'text-orange-300',
  terminal: 'text-emerald-400',
  users: 'text-teal-400',
}

/** colorFor 给侧栏图标取一个雅致的语义色 class,未命中返回柔和中性。 */
export function colorFor(name: string): string {
  return ICON_COLORS[name] ?? 'text-slate-400'
}
